name: Tests
on: [push]

jobs:
  fetch-runs:
    needs: pre-build-image
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Runs
        uses: alejio/mlflow-tracking-action@master
        id: mlflow
        with:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: $ {{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: $ {{ secrets.MLFLOW_TRACKING_PASSWORD }}
          EXPERIMENT_ID: '0'
          BASELINE_RUN_QUERY: "tags.live='1'"
          CANDIDATE_RUN_QUERY: "tags.production_candidate='1'"
      - name: test outputs
        run: |
          python -c "assert '${BOOL_COMPLETE}' == 'True'"
        env:
          BOOL_COMPLETE: ${{ steps.mlflow.outputs.BOOL_COMPLETE }}
  pre-build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Pre-Build Image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t alexsp/mlflow-tracking-action -f prebuild.Dockerfile .
        docker push alexsp/mlflow-tracking-action